language: cpp
sudo: false

addons:
  apt:
    packages:
      - libeigen3-dev
      - libcppunit-dev
      - python-sip-dev

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cppunit eigen sip ; fi

before_script:
  #build orocos_kdl
  - cd orocos_kdl
  - mkdir build
  - cd build
  - cmake -DENABLE_TESTS:BOOL=ON -DCMAKE_CXX_FLAGS:STRING="-Wall" -DCMAKE_BUILD_TYPE=${OROCOS_KDL_BUILD_TYPE} ./..
  # compile and install orocos_kdl
  - make
  - sudo make install
  - cd ../..
  #build python bindings
  - cd python_orocos_kdl
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS:STRING="-Wall" -DCMAKE_BUILD_TYPE=${OROCOS_KDL_BUILD_TYPE} ./..
  #compile and install python bindings
  - make
  - sudo make install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - sudo ldconfig
  - cd ../..

script:
  #execute orocos_kdl tests
  - cd orocos_kdl/build
  - make check
  - cd ../..
  #execute python bindings tests
  - cd python_orocos_kdl/build
  - python ../tests/PyKDLtest.py
